### ISSUE TITLE
fails to compile with 5.4.x kernel

### ISSUE THREAD

**Issue by cz172638** [smallint/tbs-usb#1]
CC [M]  /home/indy/tbs/tbs-usb/dvb-frontends/tas2101.o
/home/indy/tbs/tbs-usb/dvb-frontends/tas2101.c:908:23: error: initialization of ‘enum dvbfe_algo (*)(struct dvb_frontend *)’ from incompatible pointer type ‘int (*)(struct dvb_frontend *)’ [-Werror=incompatible-pointer-types]
  908 |  .get_frontend_algo = tas2101_get_algo,
      |                       ^~~~~~~~~~~~~~~~
/home/indy/tbs/tbs-usb/dvb-frontends/tas2101.c:908:23: note: (near initialization for ‘tas2101_ops.get_frontend_algo’)

####################

changing pointer type fix compiling, but loading modules ends with trackback and not usable system.

also tried copy newer versions from tbsdtv, failed to build

**Comment by smallint** [comment]
I fixed the compilation error. For the actual issue I have to take a closer look.
